### PR TITLE
Localization templates and Spanish localization

### PR DESCRIPTION
**Pull request by NeonKnightOA**
- Spanish localization for v469
- Localization templates for v436 (ANSI-based) and v469 (UTF-8 with BOM).

### CODE REVIEW

**Comment by shrimpza** [comment]
Hey, thanks, this is amazing.

I have to ask though; how are these used?

How does one, as a mod author, package these files in such a way that either 436 or 469 makes use of them? Is that something 469 supports? Or would we need two distributions for 436 and 469?

And I assume on the client side, these would still end up in the `/System` directory?

**Comment by NeonKnightOA** [comment]
Well, v469 has a command (coming from the UE2 games) called DumpInt, that generates automatically the .int files. This command isn't present in v436 and v451.

The files should be moved to System.

As for the other question, during my localization fixes we found that some characters weren't rendered properly in the ANSI-encoded localizations, so we switched in v469 to Unicode (more precisely UTF-8 with BOM). Considering the OldU patches are supporting 15 languages at the moment, we eventually needed the switch. Nevertheless, your mod is also played using v436/v451, so I also did templates for those old editions. The decision on which version should be used is yours.

Then again, I don't know the exact way, you may have to ask in the OldUnreal forums or the Discord channel.

**Comment by NeonKnightOA** [comment]
Here's the answer I was given by Anthrax on the official OldUnreal Discord channel:

> UTF-8 with BOM means no v436 compatibility
> That is not necessarily a bad thing though
> if you absolutely need to support both versions with your localization files, then either do plain ANSI or UTF-16LE with BOM
> but there are caveats for both cases
> For ANSI: Your own system ANSI page might not be the same page your players use
> For UTF-16LE: no Linux support

So, what files should be kept in this PR?

**Comment by NeonKnightOA** [comment]
In the end, by recommendation of Anthrax, I've decided to just leave the ANSI files for compatibility, and delete the UTF-8-BOM files; therefore the mod should work with the v436-v469 version range. Therefore in this commit there are:
- **System:** The regular .int files (there are some fixes for the mod and the maps in them) and the .est Spanish files.
- **System/Localization templates:** .int files with every line duplicated (the original and the localization) for anyone who wishes to localize this mod and its maps to their language.

**Comment by shrimpza** [comment]
Thanks @NeonKnightOA, this is great. If you have no other changes you'd like to make, I can merge this.

**Comment by NeonKnightOA** [comment]
Go on!

**Comment by NeonKnightOA** [comment]
WAIT! There's one, little more change, now that I remembered!

**Comment by NeonKnightOA** [comment]
There. This last change will guarantee that the mod shows in the Advanced Options menu. Go on!

**Pull request merged**
